services:
  mongo-express-api:
    container_name: mongo-express-api
    build:
      context: .
      target: mongo-express-api
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src # Mount code directory
    environment:
      - PORT=3000 # Set your environment variables if needed
      - MONGO_URI= # Set your environment variables if needed
    restart: unless-stopped